version: '3.5'

services:
  portainer:
    deploy:
      placement:
        constraints:
          - node.hostname == ${PLACEMENT_CONSTRAINTS_NODE_HOSTNAME:-hostname}

volumes:
  portainer-vol:
    name: ${PORTAINER_VOL_NAME}
