version: '3.9'

services:
  portainer-ce:
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared
