version: '3.5'

services:
  portainer-ce:
    deploy:
      placement:
        constraints:
          - node.hostname == ${PLACEMENT_CONSTRAINTS_NODE_HOSTNAME:-hostname}

volumes:
  data-vol:
    name: ${PORTAINER_CE_DATA_VOL_NAME}
